apiVersion: v1
kind: Service
metadata:
  name: {{ include "hometable.fullname" . }}-backend
  labels:
    {{- include "hometable.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "hometable.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
