apiVersion: v1
entries:
  hometable:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-06-14T15:34:17.180507878Z"
    description: Self-hosted recipe menu book (FastAPI + React) — connects to EXTERNAL
      Postgres + MinIO
    digest: 9b5c2923267b9773340e477d486857a175aa3d0b8e1bbe36698859b5e6c106fc
    home: https://github.com/kr4t0n/hometable
    keywords:
    - recipes
    - fastapi
    - react
    name: hometable
    sources:
    - https://github.com/kr4t0n/hometable
    type: application
    urls:
    - https://kr4t0n.github.io/hometable/helm/hometable-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-14T15:34:17.179918127Z"
